# fly.toml app configuration file generated for binar-rental-backend-app on 2023-12-15T15:22:55+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "binar-rental-backend-app"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8060
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
